# -*- coding: utf-8 -*-
"""TP2_Data-types.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbrFwL_jOAu_HVXvM_SxctZUBptFmM2f

# **TP2 Data Types and `if` Structure**
## $\color{blue}{\text{Exercise 1 - Even or odd numbers? }}$
Ask the user to enter a number then display whether it is even or odd?
"""

nb = int(input("Please type a number: "))
if nb % 2 == 0:
     print("This is an even number.")
else:
     print("This is an odd number")

"""## $\color{blue}{\text{Exercise 2 - Ticket prices }}$
The price for visting a castle is as following:
+  **free** for children between 0 and 11 years old
+  **5 euros** for children between 12 and 17 years old and for adults over 60
+  **10 euros** for adults (18-59)

Write  a  program  that  asks  for  the  user’s  age  and  returns  the  price  charged.
"""

age_u=int(input("Enter your age: "))
if age_u<=11:
    print("Ticket price: free")
elif (age_u >11 and age_u<18) or age_u >=60 :
    print("Ticket price: 5 euros")
else:
    print("Ticket price: 10 euros")

"""## $\color{blue}{\text{Exercise 3 - How much to pay employees? }}$
Write a program to ask the user for hours and rate per hour to compute gross pay, give the employee **1.5 times** the hourly rate for hours worked above **40 hours**.
"""

hours = float(input("Enter hours: "))
rate = float(input("Enter rate: "))
if hours > 40:
  pay = 40*rate + (hours-40)*(1.5*rate)
else:
  pay = hours * rate
print("The pay is: ",pay)

"""## $\color{blue}{\text{Exercise 4 - Which type? }}$
Write a program to check the type of input that the user entered from the keyboard. 

$\color{green}{\text{Hints:}}$ 
+ `input()` function gets the user's input(which can be `str`,`int`,`float`... data) and returns always a string object. 
+ You can use `str()`,`int()` and `float()`functions in this exercice 
"""

x = input("Enter something:")

if type(int(x)) == int:
    print(x, " is integer object.")    
elif type(float(x)) == float:
    print(x, "  is float object.") 
elif type(x) == str:
    print(x, " is str object. ")          
else:
    print(x, " is not float, int or string object")

"""### $\color{orange}{\text{Q 1:}}$ Why the previous program didn't work when the user entered a float number? Have you identified other issues with this program?


### $\color{orange}{\text{Q 2:}}$ What does ```try``` ... ```except``` structure do in the following program?

"""

x = input("Enter something:")
try:
    if type(int(x)) == int:
        print(x, " is integer object.")    
    elif type(float(x)) == float:
        print(x, "  is float object.") 
    elif type(x) == str:
        print(x, " is str object. ")      
except:
    print(x, " is not float, int or string object")

"""### $\color{orange}{\text{Q 3:}}$ What does the built-in function `eval()`do in the following program?"""

x = input("Enter something:")
try:
    if type(eval(x)) == int:
        print(x, " is integer object.")  
    elif type(eval(x)) == float:
        print(x, "  is float object.") 
    elif type(eval(x)) == bool:
        print(x, " is boolean object. ")      
except:
    print(x, " is string object.")

"""## $\color{blue}{\text{Exercise 5 - Handle Non-numeric Input }}$
Rewrite your pay program of exercise 3 so that your program handles non-numeric input.

"""

hour = input('Enter Hours: ')
try:
  hour = float(hour)
except:
  hour = input('Error, Please enter the numeric digit:')

rate = input('Enter Rate: ')
try:
  rate = float(rate)
except:
  rate=input('Error, Please enter the numeric digit:')

hour = float(hour)
rate = float(rate)
if hour<=40:
  pay = hour*rate
else:
  pay = 40*rate + (hour-40)*(1.5*rate)
print("The pay is: ",pay)